-- DROP TABLE IF EXISTS `tbl_certificados`;
CREATE TABLE `tbl_certificados` (
  `CertID` int(11) NOT NULL AUTO_INCREMENT,
  `Usu_ID` int(11) DEFAULT '0',  
  `anio` int(11) NOT NULL,
  `mdl_cur_id` int(11) NOT NULL,
  `mdl_cur_fullname` varchar(200) NOT NULL DEFAULT '',
  `mdl_cur_shortname` varchar(255) NOT NULL DEFAULT '',
  `mat_fechaini` varchar(15) DEFAULT NULL,
  `mat_fechafin` varchar(15) DEFAULT NULL,
  `mat_horalectiva` varchar(20) DEFAULT NULL,
  `mat_modalidad` varchar(20) DEFAULT NULL,
  `mat_nroevento` varchar(20) DEFAULT NULL,
  `mat_codpoi` varchar(20) DEFAULT NULL,
  `mdl_apepat` varchar(200) NOT NULL DEFAULT '',
  `mdl_apemat` varchar(200) NOT NULL DEFAULT '',
  `mdl_nombres` varchar(200) NOT NULL DEFAULT '',
  `mdl_dni` varchar(15) NOT NULL DEFAULT '',
  `mdl_entidad` varchar(300) NOT NULL DEFAULT '',
  `mdl_nivelgrado` varchar(300) NOT NULL DEFAULT '',
  `mdl_rubro` varchar(300) NOT NULL DEFAULT '',
  `mdl_depa_lab` varchar(300) NOT NULL DEFAULT '',
  `mdl_prov_lab` varchar(300) NOT NULL DEFAULT '',
  `mdl_dist_lab` varchar(300) NOT NULL DEFAULT '',
  `mdl_gradoacademico` varchar(300) NOT NULL DEFAULT '',
  `mdl_profesion` varchar(300) NOT NULL DEFAULT '',
  `mdl_cargo` varchar(300) NOT NULL DEFAULT '',
  `mdl_tipocontrato` varchar(300) NOT NULL DEFAULT '',
  `mdl_area_lab` varchar(300) NOT NULL DEFAULT '',  
  `ConCertificado` char(1) DEFAULT '0',  
  `NroCertificado` varchar(10) DEFAULT NULL,
  `NotaPractica` int(11) DEFAULT '0',
  `NotaForo` int(11) DEFAULT '0',
  `ExamenFinal` int(11) DEFAULT '0',
  `PromedioFinal` int(11) DEFAULT '0',
  `mdl_user_id` int(11) DEFAULT '0',
  `id_estado` varchar(1) DEFAULT '1',
  PRIMARY KEY (`CertID`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- select * from tbl_certificados;